### PR TITLE
Filter Socks Connection via AdminStatus

### PR DESCRIPTION
**Pull request by Z3rO-C00L**
Quality of Life improvement for when you have a ton of socks connections. Filtering by "AdminStatus is True" shows the most immediately useful socks connections - especially if you have a ton of connections already with only one of them having admin to a host.

### CODE REVIEW

**Review by ShutdownRepo — APPROVED** [review]

**Review by Dramelac — COMMENTED** [review]
Is there some code missing ? 
I don't see from where the new function do_admsocks is called, am i missing something ?

**Comment by ShutdownRepo** [comment]
Also @Z3rO-C00L, could you specify in the comments of this pull request the link to the original one in the official repo? (If applicable)

**Comment by mpgn** [comment]
Original PR from @Z3rO-C00L  https://github.com/fortra/impacket/pull/1462
But be award that a previous PR open in 2021 was also open by @Parrishjm with the same behabior and pretty much the same code. Also the function is also never called https://github.com/fortra/impacket/pull/1113 like this PR 👀

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
As per https://github.com/ThePorgs/impacket/pull/16#pullrequestreview-1248811137 and https://github.com/ThePorgs/impacket/pull/16#issuecomment-1383678144, it seems the function is never called. And there's apparently a duplicate with https://github.com/fortra/impacket/pull/1113. Waiting for some changes and more explanations/transparency pleasse...

**Comment by Parrishjm** [comment]
Well this is interesting......

One thing I did want to bring up though. This code was not meant to be called elsewhere in the code but rather called from the CLI iteself. This matches other functions in the same area such as do_startServers(). This worked last I tested it.

**Comment by Z3rO-C00L** [comment]
> Original PR from @Z3rO-C00L [fortra#1462](https://github.com/fortra/impacket/pull/1462)
> But be award that a previous PR open [fortra#1113](https://github.com/fortra/impacket/pull/1113) in 2021 was also open by @Parrishjm with the same behavior and pretty much the same code. Also the function is also never called like this PR 👀

Sorry for the delayed response (I’m dealing with COVID at the moment). I didn’t even see the previous PR for admin socks - so that’s my bad.

**Comment by Z3rO-C00L** [comment]
> As per [#16 (review)](https://github.com/ThePorgs/impacket/pull/16#pullrequestreview-1248811137) and [#16 (comment)](https://github.com/ThePorgs/impacket/pull/16#issuecomment-1383678144), it seems the function is never called. And there's apparently a duplicate with [fortra#1113](https://github.com/fortra/impacket/pull/1113). Waiting for some changes and more explanations/transparency please...

The function doesn’t need to be called anywhere else. do_admsocks adds another option “admsocks” in the CLI that reads the json array and does a fancy grep for any socks connection where AdminStatus is true. Then prints the table.

It seems only fair to use @Parrishjm code since he submitted a PR first.

**Comment by ShutdownRepo** [comment]
Thanks @Parrishjm and @Z3rO-C00L for your answers
Indeed, the function respects the format used by similar functions for interactive shell purposes
Imo we'd need to compare https://github.com/fortra/impacket/pull/1162 and https://github.com/fortra/impacket/pull/1462 and choose whatever implementation is technically best
Hope you'll feel better soon @Z3rO-C00L ✌️

**Comment by Parrishjm** [comment]
My initial code was more in line with killing all non admin tunnels rather than only showing admin tunnels. As such it was rightly requested to be usable to kill tunnels based on specific parameters.  A feature that was to large for me to handle at that time or now. 

If this PR handles showing Admin tunnels with out killing the others I see no reason not to move forward with it.

**Comment by ShutdownRepo** [comment]
> My initial code was more in line with killing all non admin tunnels rather than only showing admin tunnels. As such it was rightly requested to be usable to kill tunnels based on specific parameters. A feature that was to large for me to handle at that time or now.
> 
> If this PR handles showing Admin tunnels with out killing the others I see no reason not to move forward with it.

Agreed, let's merge

**Pull request merged**
