### PR TITLE
 Add TGS Options to TGS Requests

### PR DESCRIPTION
**Pull request by ShutdownRepo**
Original PR: https://github.com/fortra/impacket/pull/1417

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
I'm wondering if having this feature rely on an env var is the best option. In my opinion, having an optional argument could be more relevant

**Comment by mxrch** [comment]
> I'm wondering if having this feature rely on an env var is the best option. In my opinion, having an optional argument could be more relevant

I agree !

**Review by mxrch — CHANGES_REQUESTED** [review]
Would be better to provide a CLI argument instead of an environment variable

**Comment by aconite33** [comment]
@ShutdownRepo We tried getting it as a command line argument, but uhh, it's kind of a mess to get passed all the way down the file we needed it to be used. We opted for a environmental variable instead, because #lazy. I'm totally fine with it being an argument.

Of recent note, we just ran into this issue again during an engagement because EDR's are finger printing the protocol and are able to identify Impacket and CrackMapExec because of the options chosen.

I believe modifying the default ticket request to be in line with Window's defaults would reduce this ability to fingerprint the tool.

**Comment by ShutdownRepo** [comment]
100% agree on the fact the feature is needed/useful, but my point stays the same, we must pass the values in CLI args

**Comment by aconite33** [comment]
I'm all for command line arguments. We didn't investigate it much, we just wanted it get it to work when we were in the midst of our engagement. I think there were alot of modifications required to get it to pass down to that level. I haven't looked at the code in some time.

**Comment by ShutdownRepo** [comment]
Closing here, too much conflicts to handle
The best would now be to re-create PRs targeting the new 'main' branch that starts from the current Fortra's master branch

**Pull request closed without merging**
