### PR TITLE
Use LDAP paged search in GetUserSPNs.py

### PR DESCRIPTION
**Pull request by ShutdownRepo**
Original PR: https://github.com/fortra/impacket/pull/1487

### CODE REVIEW

**Review by ThePirateWhoSmellsOfSunflowers — APPROVED** [review]
Tested on a prod env. OK
See https://github.com/fortra/impacket/issues/1485 for more info

**Review by SAERXCIT — APPROVED** [review]

**Comment by ShutdownRepo** [comment]
@SAERXCIT @ThePirateWhoSmellsOfSunflowers it seems original PR (https://github.com/fortra/impacket/pull/1487) is closed and new one is https://github.com/fortra/impacket/pull/1498. I think we should close this PR and open a new one reflecting the changes of 1498 right?

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
No, it's because fixing a conflict between this repo and forta's one breaks PR on forta side. Another example is this PR https://github.com/fortra/impacket/pull/1262, I think forta will never merge it because now, Podalirius branch contains 250+ commits instead of 1 (if I remember correctly).

As Porgs branch is 260+ commits ahead of forta, I think it is no longer possible to have a clean PR system between forta/porgs.

:sunflower:

**Comment by ShutdownRepo** [comment]
Ok, understood, let's merge here
For PRs with lots of commits, fortra could always choose to squash & merge in order to keep commits history tight.
But yeah, I agreed, the more fortra waits on merging things, and the more ThePorgs progresses, the two forks will have troubles having a clean PR sync

**Pull request merged**
