### PR TITLE
[secretsdump] Add DumpSecretsOptions class for dev flexibility

### PR DESCRIPTION
**Pull request by ShutdownRepo**
Original PR : https://github.com/fortra/impacket/pull/1489

### CODE REVIEW

**Comment by n3rada** [comment]
I just saw that you chose to take this update on your repo. I was not aware of this fork specific to your tools. Do you advise me to do PR here in the future? Will the PRs made on your fork necessarily end up on the official version one day?

**Comment by ShutdownRepo** [comment]
> I just saw that you chose to take this update on your repo. I was not aware of this fork specific to your tools. Do you advise me to do PR here in the future? Will the PRs made on your fork necessarily end up on the official version one day?

This fork is not official. You should probably do your PRs on the official repo, and then here as well if you wish

**Review by n3rada — APPROVED** [review]

**Comment by Dramelac** [comment]
It's very nice! Great work @n3rada !

Regarding our fork, the point is to merge new feature / fix before de official repo to keep everything up to date, and although these changes are really good from my point of view, I don't know if they're suited to our fork. Merge these changes before the official release will create a lot of conflict for all the other PRs affecting this same script.

Once the PR is merged into the official repo, these changes will become the norm and at that point we'll be able to synchronize so that the other PRs are compatible, but until then I'm afraid it'll add to our workload to resolve all future conflicts while the official is late...

**Comment by ShutdownRepo** [comment]
Bumped this PR in the official repo, closing here

**Pull request closed without merging**
